version: '3.1'

services:

  pv211.rabbitmq:
    image: rabbitmq:3-management
    container_name: pv211.rabbitmq
    ports:
      - "5672:5672"  # Порт для AMQP (клиенты RabbitMQ)
      - "15672:15672" # Панель управления RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  pv211.redis:
    image: redis:latest
    container_name: pv211.redis
    ports:
      - "6379:6379"

  pv211.db.mariadb:
    image: mariadb:11.0
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: QweAsdZxc!23
      MYSQL_ROOT_PASSWORD: QweAsdZxc!23
      MYSQL_DATABASE: java
      MYSQL_USER: java
      MYSQL_PASSWORD: QweAsdZxc!23

  pv211.adminer:
    image: adminer
    ports:
      - 8080:8080

  pv211.phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: pv211.db
      MYSQL_ROOT_PASSWORD: QweAsdZxc!23